# 代理配置
PROXY:
    proxy: true
    proxy_url: http://127.0.0.1:10809

# 数据库配置
DATABASE:
    database: sqlite # 也不打算写其他的
    database_file: Ayachi.db

# BOT配置
TELEGRAM:
    admin_id: 718937510
    bot_token: 6906209180:AAHJAhJ3neqa3EXYLAM9cGK0zH3Dd6SYXhY
	
# 用户配置
USER:
    max_attack_duration: 120
    checkin_credit: 120